import nbformat as nbf
import os

def generate_notebook():
    nb = nbf.v4.new_notebook()

    # Introduction
    nb.cells.append(nbf.v4.new_markdown_cell(
        "# Quantum Tilted Loss and Ascending CVaR Comparison\n\n"
        "This notebook explores the performance of the **Quantum Tilted Loss Function** in solving the Number Partitioning problem "
        "and compares it directly against the implementation from the `Ascending_CVaR` repository.\n\n"
        "### 1. Mathematical Background\n"
        "The **Quantum Tilted Loss Function** is defined as:\n"
        "$$\\mathcal{L}_\\gamma(H,\\rho(\\theta)) := - \\frac{1}{\\gamma} \\log \\text{tr} \\left( e^{- \\gamma H} \\rho(\\theta) \\right)$$\n"
        "where $\gamma$ is a real parameter. As $\gamma \\to 0$, it recovers the standard expectation value. "
        "For $\gamma > 0$, it penalizes high-energy (sub-optimal) states more heavily, potentially accelerating convergence to the ground state.\n\n"
        "### 2. Objectives\n"
        "1. Reproduce the problem and solutions in Ascending CVaR.\n"
        "2. Implement the quantum tilted loss function.\n"
        "3. Compare Standard Loss, CVaR loss, and Tilted Loss.\n"
        "4. Compare performance with different fixed values of $\gamma$ (0.1, 5, 10, 20, 100).\n"
        "5. Investigate the effect of tuning $\gamma$ using different schedules (Linear, Sigmoid, Exponential, Logarithmic), in a way similar to tuning $\alpha$ in Ascending CVaR."
    ))

    # Imports
    nb.cells.append(nbf.v4.new_code_cell(
        "import math\n"
        "import numpy as np\n"
        "import scipy.optimize\n"
        "import matplotlib.pyplot as plt\n"
        "from qiskit.circuit.library import TwoLocal\n"
        "from qiskit.primitives import StatevectorSampler\n"
        "from qiskit.circuit import QuantumCircuit, ClassicalRegister, QuantumRegister\n\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n\n"
        "np.random.seed(42)"
    ))

    # VQE Class
    nb.cells.append(nbf.v4.new_code_cell(
        "class VQE():\n"
        "    def __init__(self, number_of_qubits, thetas, single_qubit_gates, two_qubit_gates, entanglement, layers, number_list, alpha):\n"
        "        self.number_of_qubits = number_of_qubits\n"
        "        self.number_list = number_list\n"
        "        self.thetas = thetas\n"
        "        self.layers = layers\n"
        "        self.alpha = alpha\n"
        "        try:\n"
        "            self.shots = int(1000/alpha) if alpha > 0.0 else 10000\n"
        "        except:\n"
        "            self.shots = 10000\n\n"
        "        qreg = QuantumRegister(self.number_of_qubits)\n"
        "        creg = ClassicalRegister(self.number_of_qubits, 'creg')\n\n"
        "        self.circuit = QuantumCircuit(qreg, creg)\n"
        "        self.circuit &= TwoLocal(self.number_of_qubits, single_qubit_gates, two_qubit_gates, entanglement, layers)\n"
        "        self.circuit.measure(range(self.number_of_qubits), creg)\n\n"
        "        sampler = StatevectorSampler()\n"
        "        pub = (self.circuit, thetas)\n\n"
        "        job = sampler.run([pub], shots=self.shots)\n"
        "        result = job.result()[0]\n"
        "        self.counts = result.data.creg.get_counts()\n\n"
        "    def get_expected_value(self):\n"
        "        avr_c = 0\n"
        "        for sample in list(self.counts.keys()):\n"
        "            y = [int(num) for num in list(sample)]\n"
        "            tmp_eng = self.cost_hamiltonian(y)\n"
        "            avr_c += self.counts[sample] * tmp_eng\n"
        "        return avr_c/self.shots\n\n"
        "    def cost_hamiltonian(self, x):\n"
        "        spins = [int(i) for i in x[::-1]]\n"
        "        total_energy = sum(self.number_list[i] * (1 if spins[i] == 0 else -1) for i in range(self.number_of_qubits))\n"
        "        return total_energy**2\n\n"
        "    def best_cost_brute(self):\n"
        "        best_cost = np.inf\n"
        "        for b in range(2**self.number_of_qubits):\n"
        "            x = [int(t) for t in reversed(list(bin(b)[2:].zfill(self.number_of_qubits)))]\n"
        "            cost = sum(self.number_list[i] * (2*x[i] - 1) for i in range(self.number_of_qubits))\n"
        "            cost = cost**2\n"
        "            if best_cost > cost:\n"
        "                best_cost = cost\n"
        "        return best_cost\n\n"
        "    def probability_of_optimal(self):\n"
        "        optimal_solution = self.best_cost_brute()\n"
        "        energies = self.exact_counts()\n"
        "        return sum(1 for energy in energies if energy == optimal_solution)/self.shots\n\n"
        "    def exact_counts(self):\n"
        "        energies = []\n"
        "        for sample in list(self.counts.keys()):\n"
        "            y = [int(num) for num in list(sample)]\n"
        "            tmp_eng = self.cost_hamiltonian(y)\n"
        "            energies.extend([tmp_eng] * self.counts[sample])\n"
        "        energies.sort(reverse=False)\n"
        "        return energies"
    ))

    # OptimizerWrapper with standard, CVaR and Tilted losses
    nb.cells.append(nbf.v4.new_code_cell(
        "class OptimizerWrapper():\n"
        "    def __init__(self, number_of_qubits, single_qubit_gates, two_qubit_gates, entanglement, layers, number_list, maxiter):\n"
        "        self.number_of_qubits = number_of_qubits\n"
        "        self.single_qubit_gates = single_qubit_gates\n"
        "        self.two_qubit_gates = two_qubit_gates\n"
        "        self.entanglement = entanglement\n"
        "        self.number_list = number_list\n"
        "        self.layers = layers\n"
        "        self.maxiter = maxiter\n"
        "        self.history = []\n\n"
        "    def get_standard_loss(self, angles):\n"
        "        vqe = VQE(self.number_of_qubits, angles, self.single_qubit_gates, self.two_qubit_gates, self.entanglement, self.layers, self.number_list, 1.0)\n"
        "        energy_expectation = vqe.get_expected_value()\n"
        "        self.history.append(energy_expectation)\n"
        "        return energy_expectation\n\n"
        "    def get_CVaR_loss(self, angles, alpha):\n"
        "        vqe = VQE(self.number_of_qubits, angles, self.single_qubit_gates, self.two_qubit_gates, self.entanglement, self.layers, self.number_list, alpha)\n"
        "        energies = vqe.exact_counts()\n"
        "        num_samples = math.ceil(len(energies)*alpha)\n"
        "        cvar = np.sum(energies[:num_samples])/num_samples\n"
        "        self.history.append(np.mean(energies)) # Store full expectation for fair plotting\n"
        "        return cvar\n\n"
        "    def get_Tilted_loss(self, angles, gamma):\n"
        "        vqe = VQE(self.number_of_qubits, angles, self.single_qubit_gates, self.two_qubit_gates, self.entanglement, self.layers, self.number_list, 1.0)\n"
        "        energies = np.array(vqe.exact_counts())\n"
        "        full_exp = np.mean(energies)\n"
        "        self.history.append(full_exp)\n\n"
        "        if gamma == 0:\n"
        "            return full_exp\n\n"
        "        min_E = np.min(energies)\n"
        "        exponent_terms = -gamma * (energies - min_E)\n"
        "        log_term = np.log(np.mean(np.exp(exponent_terms)))\n"
        "        return min_E - (1/gamma) * log_term\n\n"
        "    def optimize(self, initial_angles, loss_type='standard', param=1.0, options=None):\n"
        "        self.history = []\n"
        "        if loss_type == 'standard':\n"
        "            opt = scipy.optimize.minimize(self.get_standard_loss, x0=tuple(initial_angles), method='COBYLA', options={'maxiter': self.maxiter})\n"
        "            best_angles = opt.x\n"
        "        elif loss_type == 'cvar':\n"
        "            opt = scipy.optimize.minimize(self.get_CVaR_loss, x0=tuple(initial_angles), args=(param,), method='COBYLA', options={'maxiter': self.maxiter})\n"
        "            best_angles = opt.x\n"
        "        elif loss_type == 'tilted':\n"
        "            opt = scipy.optimize.minimize(self.get_Tilted_loss, x0=tuple(initial_angles), args=(param,), method='COBYLA', options={'maxiter': self.maxiter})\n"
        "            best_angles = opt.x\n"
        "        elif loss_type == 'ascending_cvar':\n"
        "            steps = options['steps']\n"
        "            ascending_factor = options['ascending_factor']\n"
        "            alpha = param\n"
        "            step = 1\n"
        "            current_angles = tuple(initial_angles)\n"
        "            while step < steps:\n"
        "                opt = scipy.optimize.minimize(self.get_CVaR_loss, x0=current_angles, args=(alpha,), method='COBYLA', options={'maxiter': self.maxiter})\n"
        "                current_angles = opt.x\n"
        "                alpha += ascending_factor\n"
        "                step += 1\n"
        "            best_angles = current_angles\n"
        "        elif loss_type == 'tuned_tilted':\n"
        "            steps = options['steps']\n"
        "            schedule = options['schedule']\n"
        "            gamma_start = options['gamma_start']\n"
        "            gamma_end = options['gamma_end']\n"
        "            \n"
        "            step = 1\n"
        "            current_angles = tuple(initial_angles)\n"
        "            while step < steps:\n"
        "                t = step - 1\n"
        "                T = steps - 1\n"
        "                if schedule == 'linear':\n"
        "                    gamma = gamma_start + (gamma_end - gamma_start) * (t / T) if T > 0 else gamma_start\n"
        "                elif schedule == 'sigmoid':\n"
        "                    gamma = gamma_start + (gamma_end - gamma_start) / (1 + np.exp(-10 * (t/T - 0.5))) if T > 0 else gamma_start\n"
        "                elif schedule == 'exponential':\n"
        "                    gamma = gamma_start * (gamma_end / gamma_start)**(t / T) if T > 0 else gamma_start\n"
        "                elif schedule == 'logarithmic':\n"
        "                    gamma = gamma_start + (gamma_end - gamma_start) * np.log(1 + t) / np.log(1 + T) if T > 0 else gamma_start\n"
        "                else:\n"
        "                    gamma = gamma_start\n\n"
        "                opt = scipy.optimize.minimize(self.get_Tilted_loss, x0=current_angles, args=(gamma,), method='COBYLA', options={'maxiter': self.maxiter})\n"
        "                current_angles = opt.x\n"
        "                step += 1\n"
        "            best_angles = current_angles\n\n"
        "        vqe_eval = VQE(self.number_of_qubits, best_angles, self.single_qubit_gates, self.two_qubit_gates, self.entanglement, self.layers, self.number_list, 0.1)\n"
        "        prob_optimal = vqe_eval.probability_of_optimal()\n"
        "        return self.history.copy(), prob_optimal\n"
    ))

    # Definitions
    nb.cells.append(nbf.v4.new_code_cell(
        "# Setup the Number Partitioning problem on 8 qubits (to balance run time in notebook)\n"
        "number_of_qubits = 8\n"
        "number_list = [np.random.randint(0, 100) for _ in range(number_of_qubits)]\n"
        "print(f\"Number list for partitioning: {number_list}\")\n\n"
        "layers = 2\n"
        "single_qubit_gates = 'ry'\n"
        "two_qubit_gates = 'cz'\n"
        "entanglement  = 'linear'\n"
        "maxiter = int((layers+1)*3*number_of_qubits/2)\n"
        "init_thetas = [np.random.uniform(0, 2*np.pi) for _ in range((layers+1)*number_of_qubits)]\n\n"
        "opt_wrapper = OptimizerWrapper(number_of_qubits, single_qubit_gates, two_qubit_gates, entanglement, layers, number_list, maxiter)\n"
    ))

    # Task 3: Compare Losses
    nb.cells.append(nbf.v4.new_markdown_cell(
        "## Task 3: Compare Standard Loss, CVaR loss, and Tilted Loss"
    ))
    nb.cells.append(nbf.v4.new_code_cell(
        "print(\"1. Optimizing Standard Loss...\")\n"
        "hist_std, prob_std = opt_wrapper.optimize(init_thetas, loss_type='standard')\n\n"
        "print(\"2. Optimizing Setup CVaR (alpha=0.20)...\")\n"
        "hist_cvar, prob_cvar = opt_wrapper.optimize(init_thetas, loss_type='cvar', param=0.20)\n\n"
        "print(\"3. Optimizing Ascending CVaR (alpha starts 0.01, ascends by 0.03 for 15 steps)...\")\n"
        "hist_asc_cvar, prob_asc_cvar = opt_wrapper.optimize(init_thetas, loss_type='ascending_cvar', param=0.01, options={'steps': 15, 'ascending_factor': 0.03})\n\n"
        "print(\"4. Optimizing Fixed Tilted Loss (gamma=5.0)...\")\n"
        "hist_tilted, prob_tilted = opt_wrapper.optimize(init_thetas, loss_type='tilted', param=5.0)\n\n"
        "print(\"\\n--- Probabilities of Sampling Optimal Solution ---\")\n"
        "print(f\"Standard Loss      : {prob_std:.4f}\")\n"
        "print(f\"CVaR (alpha=0.2)   : {prob_cvar:.4f}\")\n"
        "print(f\"Ascending CVaR     : {prob_asc_cvar:.4f}\")\n"
        "print(f\"Tilted (gamma=5.0) : {prob_tilted:.4f}\")\n\n"
        "plt.figure(figsize=(10, 6))\n"
        "plt.plot(hist_std, label='Standard Loss', alpha=0.7)\n"
        "plt.plot(hist_cvar, label='CVaR (alpha=0.2)', alpha=0.7)\n"
        "plt.plot(hist_asc_cvar, label='Ascending CVaR', alpha=0.7)\n"
        "plt.plot(hist_tilted, label='Tilted Loss (gamma=5)', alpha=0.7)\n"
        "plt.xlabel(\"Function Evaluations\")\n"
        "plt.ylabel(\"Expectation Value <H>\")\n"
        "plt.title(\"Comparison: Expected Energy during Optimization\")\n"
        "plt.legend()\n"
        "plt.grid(True)\n"
        "plt.show()\n"
    ))

    # Task 4: Compare gamma values
    nb.cells.append(nbf.v4.new_markdown_cell(
        "## Task 4: Fix Gamma Values Comparison\n"
        "Compare the algorithm performance with different fixed values of $\gamma$ (0.1, 5, 10, 20, 100)."
    ))
    nb.cells.append(nbf.v4.new_code_cell(
        "gamma_values = [0.1, 5, 10, 20, 100]\n"
        "gamma_histories = {}\n"
        "gamma_probs = {}\n\n"
        "for gamma in gamma_values:\n"
        "    print(f\"Optimizing Tilted Loss with gamma={gamma}...\")\n"
        "    hist, prob = opt_wrapper.optimize(init_thetas, loss_type='tilted', param=gamma)\n"
        "    gamma_histories[gamma] = hist\n"
        "    gamma_probs[gamma] = prob\n\n"
        "print(\"\\n--- Probabilities of Sampling Optimal Solution ---\")\n"
        "for gamma in gamma_values:\n"
        "    print(f\"gamma={gamma:<5} : {gamma_probs[gamma]:.4f}\")\n\n"
        "plt.figure(figsize=(10, 6))\n"
        "for gamma in gamma_values:\n"
        "    plt.plot(gamma_histories[gamma], label=f'gamma={gamma}', alpha=0.8)\n"
        "plt.xlabel(\"Function Evaluations\")\n"
        "plt.ylabel(\"Expectation Value <H>\")\n"
        "plt.title(\"Tilted Loss Performance across Gamma values\")\n"
        "plt.legend()\n"
        "plt.grid(True)\n"
        "plt.show()\n"
    ))

    # Task 5: Different Schedules
    nb.cells.append(nbf.v4.new_markdown_cell(
        "## Task 5: Investigating tuning $\gamma$ Schedules\n\n"
        "Here we tune $\gamma$ identical to how $\\alpha$ is tuned in Ascending CVaR (updating $\gamma$ at discrete steps through successive COBYLA passes).\n"
        "Using $\gamma_{start}=0.1$ going to $\gamma_{end}=20.0$ over 15 steps."
    ))
    nb.cells.append(nbf.v4.new_code_cell(
        "schedules = ['linear', 'sigmoid', 'exponential', 'logarithmic']\n"
        "sched_histories = {}\n"
        "sched_probs = {}\n\n"
        "gamma_start = 0.1\n"
        "gamma_end   = 20.0\n"
        "steps = 15\n\n"
        "for sched in schedules:\n"
        "    print(f\"Optimizing Tuned Tilted Loss with schedule: {sched}...\")\n"
        "    opts = {\n"
        "        'steps': steps,\n"
        "        'schedule': sched,\n"
        "        'gamma_start': gamma_start,\n"
        "        'gamma_end': gamma_end\n"
        "    }\n"
        "    hist, prob = opt_wrapper.optimize(init_thetas, loss_type='tuned_tilted', options=opts)\n"
        "    sched_histories[sched] = hist\n"
        "    sched_probs[sched] = prob\n\n"
        "print(\"\\n--- Probabilities of Sampling Optimal Solution ---\")\n"
        "print(f\"Ascending CVaR        : {prob_asc_cvar:.4f}\")\n"
        "for sched in schedules:\n"
        "    print(f\"Tilted ({sched:<11}) : {sched_probs[sched]:.4f}\")\n\n"
        "plt.figure(figsize=(12, 7))\n"
        "plt.plot(hist_asc_cvar, label='Ascending CVaR', color='black', linewidth=2, linestyle='--')\n\n"
        "for sched in schedules:\n"
        "    plt.plot(sched_histories[sched], label=f'Tilted (sched={sched})', alpha=0.8)\n"
        "plt.xlabel(\"Function Evaluations\")\n"
        "plt.ylabel(\"Expectation Value <H>\")\n"
        "plt.title(f\"Gamma Schedules vs Ascending CVaR (Steps={steps})\")\n"
        "plt.legend()\n"
        "plt.grid(True)\n"
        "plt.show()\n"
    ))

    output_path = os.path.abspath('tilted_cvar_comparison.ipynb')
    with open(output_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    
    return output_path

if __name__ == '__main__':
    created_path = generate_notebook()
    print(f'Notebook successfully generated at: {created_path}')
